#!/bin/sh

app/console doctrine:generate:entities CfpConferenceBundle:Conference
app/console doctrine:generate:entities CfpCfpBundle:CfpTalk
app/console doctrine:generate:entities CfpCfpBundle:Cfp
app/console doctrine:generate:entities CfpCfpBundle:Vote
app/console doctrine:generate:entities CfpUserBundle:User

app/console doctrine:schema:update --dump-sql

if [ "$1" = "force" ] ; then 
app/console doctrine:schema:update --force
fi
